### ISSUE TITLE
Error: Cannot find symbol com.centaurwarchief.smslistener

### ISSUE THREAD

**Issue by mitesh-mutha** [CentaurWarchief/react-native-android-sms-listener#12]
I have React Native 0.29.1 version. I followed the instructions given to install the package. However, when I run react-native run-android it gives the following error

`error: cannot find symbol
import com.centaurwarchief.smslistener;` and
`error: cannot find symbol
          new SmsListener()`

**Comment by abhisheknalin** [comment]
i faced the same issue while on RN 0.29. Just use the instructions of RN<0.28 and it will work

```
Inside MainApplication.java

use this =>  import com.centaurwarchief.smslistener.SmsListenerPackage;

and this=>    new SmsListenerPackage()

```

**Comment by andreyvital** [comment]
Check the installed version. It should be:

```
import com.centaurwarchief.smslistener.SmsListenerPackage;
```

And in your `getPackages()` make sure you have: `new SmsListenerPackage()`

**Comment by mitesh-mutha** [comment]
Yes, following the instructions for RN <0.28 helped me in this case. Thank you.
