### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by julienvincent** [CentaurWarchief/react-native-android-sms-listener#15]
I'd love to use this but I will need it for both iOS and android. Do you have any plans to port this to iOS in the near future?

**Comment by CentaurWarchief** [comment]
Hey — sorry for the late answer. 

Well, unfortunately by the time I was writing this library, seemed that Apple doesn't allow to read incoming SMS messages so I don't know if we have available APIs to do that.

If you have any links to share regarding some APIs we could use to do this, I'd appreciate. Thanks!

**Comment by andreyvital** [comment]
Hey — sorry for the late answer.

Well, unfortunately by the time I was writing this library, seemed that Apple doesn't allow to read incoming SMS messages so I don't know if we have available APIs to do that.

If you have any links to share regarding some APIs we could use, I'd appreciate. Thanks!

**Comment by julienvincent** [comment]
Soon after I posted this I realized the same thing - forgot to close this. Thanks for the reply!

**Comment by andreyvital** [comment]
Nope. Thanks!

**Comment by achtan** [comment]
IOS is now supporting sms reading... pls consider implementing it

**Comment by vladakg85** [comment]
Any news on supporting this on IOS?

**Comment by vladakg85** [comment]
Any news on supporting this on IOS?

**Comment by vvusts** [comment]
Any news on supporting this on IOS?

**Comment by jerryheir** [comment]
Hello @andreyvital . This is now valid for iOS

**Comment by JayeshPatil-Dev** [comment]
Hello @andreyvital  Any update for ios?

**Comment by andreyvital** [comment]
@JayeshPatil-Dev sorry, but I am not actively maintaining this library.
