### ISSUE TITLE
Compile Error : new smslistener() in MainApplication.js

### ISSUE THREAD

**Issue by ramancodians** [CentaurWarchief/react-native-android-sms-listener#16]
![asdasd3333](https://cloud.githubusercontent.com/assets/2060784/21884786/bb5eaef0-d8da-11e6-8810-2693106e04b3.PNG)

here is the error. I followed the installations steps. Please help.

**Comment by andreyvital** [comment]
cc @julianocomg 

Do you have any thoughts on this one?

**Comment by flaviosbert** [comment]
I followed all the instructions and faced the same problem.

Got it to work following the instructions to RN < 0.28:

import com.centaurwarchief.smslistener.SmsListenerPackage;
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new SmsListenerPackage()
    // (...)
  );
}

**Comment by andreyvital** [comment]
Thanks for the feedback, @flaviosbert.

**Comment by semiautomatix** [comment]
Still an issue. Will try @flaviosbert's suggestion.

**Comment by andreyvital** [comment]
Hey @semiautomatix — still an issue after attempting @flaviosbert's suggestion?

**Comment by semiautomatix** [comment]
Thanks @centaurwarchief. @flaviobert's suggestion worked a charm :-)

**Comment by andreyvital** [comment]
Thanks @semiautomatix. And sorry for the delayed reply.
