### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by stephentan** [CentaurWarchief/react-native-android-sms-listener#17]
after I have setup this module, 

I tried to run-android but I get the following error: 
TypeError: Cannot read property 'message' of undefined

------ Here's the logs ----------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-android-sms-listener'.
   > failed to find Build Tools revision 23.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.349 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:32854) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

-----------------------

Wondering if this is an issue with react-native version compatibility.
"react-native": "^0.40.0",

**Comment by andreyvital** [comment]
🤔 

That's probably in your own code? — doesn't look like a Java error.

**Comment by stephentan** [comment]
@CentaurWarchief Thanks for the quick reply. 
I made sure I left index.android.js untouched as well.. after creating the project.

After doing react-native init I just followed the instruction on how to setup this module then immediately run-android and hmm.. another thing is.. it already failed during the build phase..

**Comment by stephentan** [comment]
@CentaurWarchief 
Sorry for taking up your time.
The error was misleading. It turned out it's a problem with missing android sdk 23.0.2
Please disregard this. I found the correct error when doing ./gradlew build

**Comment by andreyvital** [comment]
Thanks, @stephentan.
