### ISSUE TITLE
Not listening

### ISSUE THREAD

**Issue by nazarTrynko** [CentaurWarchief/react-native-android-sms-listener#19]
Hi! I have added everything like in guide, added listener to my view, but it does not enter listener's callback

**Comment by andreyvital** [comment]
Can you share a code snippet of how you're using it?

**Comment by nazarTrynko** [comment]
I tried to put it in componentDid/WillMount
`componentDidMount() {
    SmsListener.addListener(message => {
      console.log(message)
    })
  }`

and before component:
```
import SmsListener from 'react-native-android-sms-listener

SmsListener.addListener(message => {
  console.log(message)
})

export default class SmsView extends Component {
```

**Comment by andreyvital** [comment]
Right. I'll try to troubleshoot/reproduce this later.

**Comment by nazarTrynko** [comment]
Thanks! Looking forward to hearing from you!

**Comment by jucastilhoduarte** [comment]
@nazarTrynko What's your RN version?

**Comment by nazarTrynko** [comment]
@julianocomg 0.43

**Comment by jucastilhoduarte** [comment]
@nazarTrynko 
I've tested with 0.44.1 with no problems (but the API of these two versions is the same). Please, remove the module from your project, including via npm, and execute the following commands:

- npm install --save react-native-android-sms-listener
- react-native link react-native-android-sms-listener

Try again, and give us a feedback

**Comment by nazarTrynko** [comment]
@julianocomg thank you for response. I tried your approach, but unfortunately it didn't help =(

**Comment by nazarTrynko** [comment]
![image](https://user-images.githubusercontent.com/10981576/26882713-cb89cb0c-4ba3-11e7-932a-602805703386.png)

I also see that EmitterSubscription does not have context and _currentSubscription. Maybe something about those is wrong

**Comment by ghost** [comment]
Hi nazarTrynko,

After include everything like in guide, have you sent an SMS through telnet protocol?
When a SMS arrives to your phone then the listener acts and you can see your console.log

**Comment by nazarTrynko** [comment]
@lmmaeso Hi, well, I used sms simulation from AVD emulator extended control and also tried it with real sms on my device

**Comment by nazarTrynko** [comment]
Okay, so the solution was just to add permission for sms for application in Settings => Apps. Cheers =)

**Comment by andreyvital** [comment]
🍻
