### ISSUE TITLE
How can I listen to sms with the app closed?

### ISSUE THREAD

**Issue by asystat** [CentaurWarchief/react-native-android-sms-listener#24]
Hey first of all thanks for the code!
Is there a way of keeping this listener susceptible to sms's even when the app was totally killed?

Thanks

**Comment by andreyvital** [comment]
Hey @asystat — thanks for reporting this "known issue". I would need some time to figure this out and write some code, which quite frankly, I don't have that time now. Hate to disappoint. However, if you have some to spare and Java coding skills, feel free to go ahead and move a PR — I would totally support and love to get it merged.

Thanks, sorry. Really.

**Comment by beakshy** [comment]
@CentaurWarchief would you be interested in doing this as a paid job?

**Comment by dattran92** [comment]
@beakshy Do you still need it? Maybe I can help.

**Comment by kamleshsindhal08** [comment]
@beakshy, Yes, Help me.
