### ISSUE TITLE
React Native How to auto fetch the OTP in the textfield from the mobile sms 

### ISSUE THREAD

**Issue by SathishSaminathan** [CentaurWarchief/react-native-android-sms-listener#25]
I want to auto fetch the OTP which is coming in the form of  SMS

**Comment by andreyvital** [comment]
Any reference of what getter method should be called to retrieve that info out of the incoming message? Thanks

**Comment by RishavKumar-3796** [comment]
[  let OTPRegex = /^\b\d{ 4}\b/
        let final = OTPRegex.test(event.message)
        alert("message==>" + final);](url)
