### ISSUE TITLE
Deprecation message

### ISSUE THREAD

**Issue by khrizt** [CentaurWarchief/react-native-android-sms-listener#26]
Hi,

I'm starting to use your library and I've noticed that a message appears during compilation:

`Note: [path]/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/helpers/ApplicationBadgeHelper.java uses or overrides a deprecated API.`

I don't know if you already know that, looks like something with the icon badge.

**Comment by andreyvital** [comment]
hey @khrizt. I am not really sure what this have to do with this project. Your message/pathing leaves no clue of what could it be.

Can you enlighten a little more what's the issue and how it's related to sms-listener?

Thanks!

**Comment by khrizt** [comment]
Sorry, you're right. I was too sleepy on monday morning :(

**Comment by khrizt** [comment]
Sorry man, I saw the deprecation message but I copied another one, this is the one I wanted to paste:
`
Note: node_modules/react-native-android-sms-listener/android/src/main/java/com/centaurwarchief/smslistener/SmsReceiver.java uses or overrides a deprecated API.`

It's only a notice, but just FYI.

**Comment by andreyvital** [comment]
@khrizt will look into it. Thanks
