### ISSUE TITLE
Changes needed for gradle 3.0.1 compatibility

### ISSUE THREAD

**Issue by pacamara** [CentaurWarchief/react-native-android-sms-listener#30]
Some minor changes are needed for gradle 3.0.1 compatibility: in android/build.gradle:
* Remove the `buildToolsVersion`, gradle now specifies a default and the current value conflicts with that.
* Declare dependencies using `api` not `compile` per https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

We are currently hacking these changes with a script in status.im, and would rather it is fixed upstream. Thanks!

Parent issue: https://github.com/status-im/status-react/issues/3037

**Comment by appielife** [comment]
The package was working before but once i updated to gradle 3 it stoppped working . 
Have already done the above two steps , still not working . 
Any help ?

**Comment by appielife** [comment]
Figured out the package is not working for android 8.0 and above. 
Can somebody have a look and try to fix .. ?

**Comment by telmen** [comment]
any news?
