### ISSUE TITLE
Android Oreo (Api Version>=26 ) not working 

### ISSUE THREAD

**Issue by appielife** [CentaurWarchief/react-native-android-sms-listener#31]
The package is not working for android version greater than 8. 
https://developer.android.com/guide/components/broadcast-exceptions.html

**Comment by gj1118** [comment]
Can someone please confirm ? 

Thanks
Gagan

**Comment by ghost** [comment]
Confirmed. Not working for API Version >= 26

**Comment by kr4ckhe4d** [comment]
Solved the issue by Requesting SMS Read permission and SMS Receive permissions when starting the react native app.

`import { PermissionsAndroid } from 'react-native';`
  
`componentDidMount() {`
    `this.requestReadSmsPermission();`
`}`

`async requestReadSmsPermission() {`
`    try {`
`      var granted = await PermissionsAndroid.request(`
`        PermissionsAndroid.PERMISSIONS.READ_SMS,`
`        {`
`          title: "Auto Verification OTP",`
`          message: "need access to read sms, to verify OTP"`
        `}`
`      );`
`      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
`        
`console.log("sms read permissions granted", granted);
`        
`granted = await PermissionsAndroid.request(
`          
`PermissionsAndroid.PERMISSIONS.RECEIVE_SMS,{
`            
`title: "Receive SMS",`
           ` message: "Need access to receive sms, to verify OTP"`
`          }`
`        );`
`        if (granted === PermissionsAndroid.RESULTS.GRANTED) {`
`          console.log("RECEIVE_SMS permissions granted", granted);`
`        } else {`
`          console.log("RECEIVE_SMS permissions denied");`
`        }`
`      } else {`
`        console.log("sms read permissions denied");`
`      }
`    
`} catch (err) {`
`      console.log(err);`
`    }`
 ` }`

**Comment by ckOfor** [comment]
```Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.```

**Comment by ironhide0396** [comment]
Tried the above steps , but still cant seem to make it work .
Permissions always return NEVER_ASK_AGAIN .
I have tried uninstalling the app,clearing data,changing version number but still of no use.
Any other workaround or fix for this issue ?

**Comment by shubham2102** [comment]
Ask for READ_SMS as well as RECEIVE_SMS permission, it will work in sdk version 28.

**Comment by MajdAbuRoqa** [comment]
tried the above solution , permissions granted but the message not read

**Comment by PragyaSingla** [comment]
Tried integrating this library but its not auto reading messages. Please provide any solution

**Comment by venkatesh-appoids** [comment]
@kr4ckhe4d  you made my day
