### ISSUE TITLE
React Native 0.56 Support

### ISSUE THREAD

**Issue by DaniAkash** [CentaurWarchief/react-native-android-sms-listener#35]
In React Native 0.56
Android projects are compiled by SDK level 26 as default

https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#android-projects-are-now-compiled-using-the-android-26-sdk

This causes the following issue with this plugin:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-android-sms-listener'.
      > The SDK Build Tools revision (23.0.2) is too low for project ':react-native-android-sms-listener'. Minimum required is 25.0.0
```
It'd be helpful to know if any work arounds are available until this plugin supports 0.56

**Comment by FransTwisk** [comment]
You can work around this by overwriting SDK version for all subprojects used: 

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion "26.0.3"
            }
        }
    }
}
```

in PROJECT/android/build.gradle file.

**Comment by DaniAkash** [comment]
Still I'd like a permanent solution...
