### ISSUE TITLE
Trigger multiple callbacks when received one sms

### ISSUE THREAD

**Issue by done134** [CentaurWarchief/react-native-android-sms-listener#38]
`if (subscription == null) {
            subscription = SmsListener.addListener(message => {
                console.info(message);
                this._smsAnalysis(message.body)
            });
        }`
![Uploading image.png…]()

_smsAnalysis  function is called multiple times when received one sms

**Comment by ZuhaKarim** [comment]
Were you able to figure out this issue? HOW DID YOU DO IT PLEASE GUIDE ME.

**Comment by vgm8** [comment]
I'm having the same problem. When I send a sms with accents it will call two times. 
For example, if I send the message: `Sent from your Twilio trial account - el código que has seleccionado es 123457`

First time is called with: 
`Sent from your Twilio trial account - el código que has seleccionad`

Second time is called with:
`o es 123457`

it looks like it is dividing de message in two. Any idea why? Thanks
