### ISSUE TITLE
Doesn't work on android simulator, but works on android device.

### ISSUE THREAD

**Issue by mojtabamarashee** [CentaurWarchief/react-native-android-sms-listener#39]
Doesn't work on android simulator (android 8 , API 26) , but works on android device (android 5.1).

Is it about API versions?

Thanks

**Comment by jerryheir** [comment]
Does the Android emulator happen to have a slot for the sim card that receives the sms

**Comment by manuelbds** [comment]
Actually, you can send fake SMS at the simulator, @jerryheir

**Comment by xiaokyo** [comment]
> Actually, you can send fake SMS at the simulator, @jerryheir

how to send fake SMS to the emulator?

**Comment by souzasmatheus** [comment]
@xiaokyo Once the emulator is running, click on those three dots and another window with extended controls should show up
![Captura de Tela 2020-04-24 às 20 42 19](https://user-images.githubusercontent.com/37983247/80264924-2d21c800-866c-11ea-9cfe-34581f004f14.png)
