### ISSUE TITLE
got this error "Execution failed for task ':react-native-android-sms-listener:verifyReleaseResources'."

### ISSUE THREAD

**Issue by eshantbist** [CentaurWarchief/react-native-android-sms-listener#40]
Any solution for above error?

**Comment by smrd1998** [comment]
i see this error when i want to get release
any body have solution ?

**Comment by Sylchauf** [comment]
Try this code in /android/build.gradle (works for me)

> subprojects {
>   project.configurations.all {
>       afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion 26
>                 buildToolsVersion '26.0.2'
>             }
>         }
>     }
>      resolutionStrategy.eachDependency { details ->
>         if (details.requested.group == 'com.android.support'
>               && !details.requested.name.contains('multidex') ) {
>            details.useVersion "26.0.2"
>         }
>      }
>   }
> }


Thanks to https://github.com/facebook/react-native/issues/19239#issuecomment-388600147

**Comment by reactdevrocks** [comment]
still not able to generate release build. @Sylchauf after your suggestion too.
