### ISSUE TITLE
Does not work for Android 8 and above 

### ISSUE THREAD

**Issue by kush11** [CentaurWarchief/react-native-android-sms-listener#41]
For the android version less than 8 its working fine but for the above, it is not working

**Comment by riazXrazor** [comment]
any fixes yet for >= 8

**Comment by Sylchauf** [comment]
It's working with the new permissions

see https://github.com/CentaurWarchief/react-native-android-sms-listener/issues/31

**Comment by kush11** [comment]
The problem is solved by adding the permission
