### ISSUE TITLE
Application crashed after  receiving SMS

### ISSUE THREAD

**Issue by Ahmedfathyarafa** [CentaurWarchief/react-native-android-sms-listener#46]
The listener is working well and the body of the received message is logged successfully but the application is crashing immediately after receiving the SMS.

Any solution ??
@andreyvital

**Comment by devanshsadhotra25** [comment]
code>?

**Comment by Ahmedfathyarafa** [comment]
@devanshsadhotra25

Here's the code 

```
import SmsListener from 'react-native-android-sms-listener'

componentDidMount(){
    SmsListener.addListener(message => {
        console.info(message)
    })
}

```
after receiving the SMS I can see the message in the console .
but once the message received the app is closed.

And here is the error :

![WhatsApp Image 2019-07-27 at 12 05 55 AM](https://user-images.githubusercontent.com/16071974/61984050-11b55e00-b003-11e9-8e67-dcfd588f6ccf.jpeg)

**Comment by Borhanof** [comment]
I'm facing the same issue here and the issue is not solved
