### ISSUE TITLE
Listen in the background

### ISSUE THREAD

**Issue by DarrylD** [CentaurWarchief/react-native-android-sms-listener#6]
Is there anyway for this to listen while the application is in the background?

**Comment by andreyvital** [comment]
Not sure, will check.

**Comment by DarrylD** [comment]
I just tested and it's only working while the app is active. Is it possible to listen while in the background?

**Comment by stefanoTron** [comment]
that would be awesome! :) 👍

**Comment by stefanoTron** [comment]
It works if you do this in `SmsListenerModule.java`

``` java
public void onHostPause() {
     //unregisterReceiver(mReceiver);
}
```

**Comment by flaviosbert** [comment]
@CentaurWarchief it works perfectly in background, but after a while I think the app is closed by the OS and it stops listening.

I noticed a method called onHostDestroy, maybe commenting the "unRegisterReceiver" in it will do the job. Do you think it could cause me any trouble?

**Comment by gajju3588** [comment]
Hey, 

For me its not detecting any sms when App dies. Works fine when app is in background. 
 I tried with the mentioned changes in thread. Anything i might be missing ?

**Comment by trevorwhealy** [comment]
👋 @CentaurWarchief or @littletower 

Commenting out `unregisterReceiver(mReceiver);` from both the `onHostPause` and `onHostDestroy` SmsListenerModule.java seem to allow this utility to work in the background.

However, I'm curious if there is any possible way for this to run when the app is no longer open or closed? That would add tremendous value, and I have not been able to configure it as of yet. 

I've been suggested to try using https://www.npmjs.com/package/react-native-background-task or  https://facebook.github.io/react-native/docs/headless-js-android.html itself, but I just figured I might as well ask if anyone else has had any luck running this utility even if the app is closed.

**Comment by shirshak55** [comment]
is there any elegant solution to listen sms in background?

**Comment by jitendra-koodo** [comment]
> 👋 @CentaurWarchief or @littletower
> 
> Commenting out `unregisterReceiver(mReceiver);` from both the `onHostPause` and `onHostDestroy` SmsListenerModule.java seem to allow this utility to work in the background.
> 
> However, I'm curious if there is any possible way for this to run when the app is no longer open or closed? That would add tremendous value, and I have not been able to configure it as of yet.
> 
> I've been suggested to try using https://www.npmjs.com/package/react-native-background-task or https://facebook.github.io/react-native/docs/headless-js-android.html itself, but I just figured I might as well ask if anyone else has had any luck running this utility even if the app is closed.

Did you find a solution?

**Comment by tarunteckedge** [comment]
Hi

Is there a solution for this?

**Comment by shirshak55** [comment]
@tarunteckedge you can try kotlin if u are on andriod?

**Comment by tarunteckedge** [comment]
@shirshak55 I'm a newbie in react-native. But if you point some links to me, I can definitely get it to work.

**Comment by jitendra-koodo** [comment]
@tarunteckedge  You might have to create a separate background service outside ReactNative using Java/Kotlin.

**Comment by hamidashoor** [comment]
is there any possible way for this to run when the app is  closed with 'react-native-background-actions'?

**Comment by itsAkky** [comment]
SMS Reader Using React Native  

 

To read incoming SMS when app is in active state: 

(For reference : https://snyk.io/advisor/npm-package/react-native-android-sms-listener ) 

Installation 

$ npm install --save react-native-android-sms-listener  

$ react-native link react-native-android-sms-listener  

Manual Installation 

For a manual installation, all you need to do to use this so-called utility is: 

android/settings.gradle 

include ':react-native-android-sms-listener'  

project(':react-native-android-sms-listener').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-android-sms-listener/android')  

android/app/build.gradle 

dependencies { compile project(':react-native-android-sms-listener') // (...) }  

MainApplication.java 

import com.centaurwarchief.smslistener.SmsListenerPackage;  

 

Comment bellow code 

@Override 

protected List<ReactPackage> getPackages() { 

@SuppressWarnings("UnnecessaryLocalVariable") 

List<ReactPackage> packages = new PackageList(this).getPackages(); 

// Packages that cannot be autolinked yet can be added manually here, for example: 

// packages.add(new MyReactNativePackage()); 

return packages; 

} 

 

 

And add this(below) code: 

@Override protected List<ReactPackage> getPackages() { return Arrays.<ReactPackage>asList( new MainReactPackage(), new SmsListenerPackage() // (...) ); } 

 

EVEN AFTER FOLLOWING ABOVE STEPS SOME ERROS WILL OCCURE TO FIX THEM ADD: 

 

Add following permission to AndroidManifest.xml  

<uses-permission android:name="android.permission.RECEIVE_SMS" />  

<uses-permission android:name="android.permission.READ_SMS" />  

 

Add following code to MainApplication.java 

import java.util.List; 

import java.util.Arrays; 

import com.facebook.react.shell.MainReactPackage; 

import com.facebook.react.ReactPackage; 

 

REMOVE EXISTING CODE FROM app.js & PASTE BELLOW CODE 

import React from 'react'; 

import { StyleSheet, Text, View } from 'react-native'; 

import { PermissionsAndroid } from 'react-native'; 

import SmsListener from 'react-native-android-sms-listener'; 

 

export default class App extends React.Component { 

constructor() { 

super(); 

this.SMSReadSubscription = {}; 

} 

 

async requestReadSmsPermission() { 

try { 

var granted = await PermissionsAndroid.request( 

PermissionsAndroid.PERMISSIONS.READ_SMS, { 

title: 'Auto Verification OTP', 

message: 'need access to read sms, to verify OTP' 

} 

); 

if (granted === PermissionsAndroid.RESULTS.GRANTED) { 

alert('READ_SMS permissions granted', granted); 

console.log('READ_SMS permissions granted', granted); 

granted = await PermissionsAndroid.request( 

PermissionsAndroid.PERMISSIONS.RECEIVE_SMS, { 

title: 'Receive SMS', 

message: 'Need access to receive sms, to verify OTP' 

} 

); 

if (granted === PermissionsAndroid.RESULTS.GRANTED) { 

alert('RECEIVE_SMS permissions granted', granted); 

console.log('RECEIVE_SMS permissions granted', granted); 

SmsListener.addListener(message => { 

alert(message); 

console.log(message); 

console.log(message.body); 

 
 

//message.body will have the message. 

//message.originatingAddress will be the address. 

}); 

} else { 

alert('RECEIVE_SMS permissions denied'); 

console.log('RECEIVE_SMS permissions denied'); 

} 

} else { 

alert('READ_SMS permissions denied'); 

console.log('READ_SMS permissions denied'); 

} 

} catch (err) { 

alert(err); 

} 

} 

 
 

componentDidMount() { 

this.requestReadSmsPermission(); 

} 

 
 

render() { 

return ( 

<View style={styles.container}> 

<Text>Open up App.js to start working on your app!</Text> 

<Text>Changes you make will automatically reload.</Text> 

<Text>Shake your phone to open the developer menu.</Text> 

</View> 

); 

} 

} 

 
 

const styles = StyleSheet.create({ 

container: { 

flex: 1, 

backgroundColor: '#fff', 

alignItems: 'center', 

justifyContent: 'center', 

}, 

});

**Comment by nisith44** [comment]
this plugin save my life react-native-android-sms-listener-background 
https://www.npmjs.com/package/react-native-android-sms-listener-background

first uninstall old plugin 
npm uninstall react-native-android-sms-listener

then install this plugin 
npm install react-native-android-sms-listener-background

then import like this in you components
import SmsListener from 'react-native-android-sms-listener-background'

other all code same as the old plugin but this only run in the background only i think

**Comment by MahmoudY3c** [comment]
- After working around to find any solutions and show the comment above i removed `react-native-android-sms-listener` and installed `react-native-android-sms-listener-background` then used it together with `react-native-background-runner` and listneing direct to `com.centaurwarchief.smslistener:smsReceived` event by  `DeviceEventEmitter` everything solved and I can handle incoming messages when the app closed or phone screen locked I hope that help someone
